// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.springframework.roo.petclinic.dod;

import javax.persistence.EntityManager;
import org.springframework.context.annotation.Bean;
import org.springframework.roo.petclinic.dod.DataOnDemandConfiguration;
import org.springframework.roo.petclinic.domain.dod.PetDataOnDemand;

privileged aspect DataOnDemandConfiguration_Roo_JpaDataOnDemandConfiguration {
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    private EntityManager DataOnDemandConfiguration.entityManager;
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return EntityManager
     */
    public EntityManager DataOnDemandConfiguration.getEntityManager() {
        return entityManager;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param entityManager
     */
    public void DataOnDemandConfiguration.setEntityManager(EntityManager entityManager) {
        this.entityManager = entityManager;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return PetDataOnDemand
     */
    @Bean
    public PetDataOnDemand DataOnDemandConfiguration.petDataOnDemand() {
        return new PetDataOnDemand(getEntityManager());
    }
    
}
