// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.springframework.roo.petclinic.domain.dod;

import org.springframework.roo.petclinic.domain.Pet;
import org.springframework.roo.petclinic.domain.dod.PetFactory;

privileged aspect PetFactory_Roo_JpaEntityFactory {
    
    /**
     * Creates a new {@link Pet} with the given index.
     * 
     * @param index position of the Pet
     * @return a new transient Pet
     */
    public Pet PetFactory.create(int index) {
        Pet obj = new Pet();
        setName(obj, index);
        setSendReminders(obj, index);
        setWeight(obj, index);
        return obj;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void PetFactory.setName(Pet obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void PetFactory.setSendReminders(Pet obj, int index) {
        Boolean sendReminders = true;
        obj.setSendReminders(sendReminders);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void PetFactory.setWeight(Pet obj, int index) {
        Float weight = new Integer(index).floatValue();
        obj.setWeight(weight);
    }
    
}
